apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.graylog_db.name }}-deploy"
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.graylog_db.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.graylog_db.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.graylog_db.name }}
    spec:
      containers:
        - name: {{ .Values.graylog_db.name }}
          image: "{{ .Values.graylog_db.image }}:{{ .Values.graylog_db.tag }}"
          imagePullPolicy: {{ .Values.graylog_db.imagePullPolicy }}
      restartPolicy: Always
