apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.graylog.name }}-secret"
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  GRAYLOG_PASSWORD_SECRET: {{ .Values.graylog.secrets.GRAYLOG_PASSWORD_SECRET }}
  GRAYLOG_ROOT_PASSWORD_SHA2: {{ .Values.graylog.secrets.GRAYLOG_ROOT_PASSWORD_SHA2 }}
