apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.user_service.name }}-secret"
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  DATASOURCE_PASSWORD: {{ .Values.user_db.secrets.MYSQL_ROOT_PASSWORD }}
  DATASOURCE_USERNAME: {{ .Values.user_service.secrets.DATASOURCE_USERNAME }}
  KEYCLOAK_CLIENT_SECRET: {{ .Values.user_service.secrets.KEYCLOAK_CLIENT_SECRET }}
  KEYCLOAK_ADMIN_USERNAME: {{ .Values.keycloak.secrets.KC_BOOTSTRAP_ADMIN_USERNAME }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.keycloak.secrets.KC_BOOTSTRAP_ADMIN_PASSWORD }}
