apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.user_db.name }}-secret"
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.user_db.secrets.MYSQL_ROOT_PASSWORD }}
  MYSQL_DATABASE: {{ .Values.user_db.secrets.MYSQL_DATABASE }}
