server:
  port: 8083

spring:
  application:
    name: anime-service

  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DATABASE}
      auto-index-creation: true

  cloud:
    stream:
      function:
        autodetect: false

      kafka:
        binder:
          brokers: ${KAFKA_BOOTSTRAP_SERVERS}

      bindings:
        anime-created-out-0:
          destination: anime-events
          content-type: application/json

        anime-updated-out-0:
          destination: anime-events
          content-type: application/json

        anime-deleted-out-0:
          destination: anime-events
          content-type: application/json

        person-created-out-0:
          destination: anime-events
          content-type: application/json

        person-updated-out-0:
          destination: anime-events
          content-type: application/json

        person-deleted-out-0:
          destination: anime-events
          content-type: application/json

        user-contribution-created-out-0:
          destination: anime-events
          content-type: application/json

        user-contribution-updated-out-0:
          destination: anime-events
          content-type: application/json

        user-contribution-deleted-out-0:
          destination: anime-events
          content-type: application/json

management:
  endpoints:
    web:
      exposure:
        include: health