apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.kafka.name }}-cm"
  namespace: {{ .Release.Namespace }}
data:
  KAFKA_PROCESS_ROLES: "{{ .Values.kafka.cm.KAFKA_PROCESS_ROLES }}"
  KAFKA_NODE_ID: "{{ .Values.kafka.cm.KAFKA_NODE_ID }}"
  KAFKA_CONTROLLER_LISTENERS: "{{ .Values.kafka.cm.KAFKA_CONTROLLER_LISTENERS }}"
  KAFKA_CONTROLLER_LISTENER_NAMES: "{{ .Values.kafka.cm.KAFKA_CONTROLLER_LISTENER_NAMES }}"
  KAFKA_LISTENERS: "{{ .Values.kafka.cm.KAFKA_LISTENERS }}"
  KAFKA_ADVERTISED_LISTENERS: "{{ .Values.kafka.cm.KAFKA_ADVERTISED_LISTENERS }}"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "{{ .Values.kafka.cm.KAFKA_LISTENER_SECURITY_PROTOCOL_MAP }}"
  KAFKA_INTER_BROKER_LISTENER_NAME: "{{ .Values.kafka.cm.KAFKA_INTER_BROKER_LISTENER_NAME }}"
  KAFKA_CONTROLLER_QUORUM_VOTERS: "{{ .Values.kafka.cm.KAFKA_CONTROLLER_QUORUM_VOTERS }}"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "{{ .Values.kafka.cm.KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR }}"
