apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.keycloak.name }}-secret"
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  KC_DB_PASSWORD: {{ .Values.user_db.secrets.MYSQL_ROOT_PASSWORD }}
  KC_DB_USERNAME: {{ .Values.keycloak.secrets.KC_DB_USERNAME }}
  KC_BOOTSTRAP_ADMIN_USERNAME: {{ .Values.keycloak.secrets.KC_BOOTSTRAP_ADMIN_USERNAME }}
  KC_BOOTSTRAP_ADMIN_PASSWORD: {{ .Values.keycloak.secrets.KC_BOOTSTRAP_ADMIN_PASSWORD }}
