apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.graylog_opensearch.name }}-secret"
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  OPENSEARCH_INITIAL_ADMIN_PASSWORD: {{ .Values.graylog_opensearch.secrets.INITIAL_ADMIN_PASSWORD }}
