apiVersion: v1
kind: Service
metadata:
  namespace: {{.Release.Namespace}}
  name: "{{.Values.consul.name}}-svc"
spec:
  selector:
    app: {{ .Values.consul.name }}
  type: {{.Values.consul.service.type}}
  ports:
    - name: http
      protocol: TCP
      targetPort: {{ .Values.consul.service.http.targetPort }}
      port: {{ .Values.consul.service.http.port }}
      {{- if (eq .Values.consul.service.type "NodePort")}}
      nodePort: {{ .Values.consul.service.http.nodePort }}
      {{- end}}

    - name: dns-udp
      protocol: UDP
      targetPort: {{ .Values.consul.service.dns.targetPort }}
      port: {{ .Values.consul.service.dns.port }}

    - name: dns-tcp
      protocol: TCP
      targetPort: {{ .Values.consul.service.dns.targetPort }}
      port: {{ .Values.consul.service.dns.port }}
